### ISSUE TITLE
prtg script log output

### ISSUE THREAD

**Issue by redoracle** [rdlrt/Alternate-Jormungandr-Testnet#42]
Hi, can we integrate for the prtg script log output, a redirection of the stderr or anyway a path to logfile..
Asking this because during every node bootstrapping the prtg is using stdout as stderr, not nice to have error messages while you in the console...

**Comment by rdlrt** [comment]
[Resolved](https://github.com/rdlrt/Alternate-Jormungandr-Testnet/commit/3e917ca11a26782b6f4a075583a519b42deda85a#diff-cd7c48376d6bf11d8dbba401be2a1065)
