### ISSUE TITLE
What is the effect of low delegation % on the network ?

### ISSUE THREAD

**Issue by psychomb** [rdlrt/Alternate-Jormungandr-Testnet#6]
The testnet produces roughly 70 block per epochs, but contains 360 slots. 
Active pools contain approx 5M ADAs and undelegated is 97M

Could the owner of the faucet try an experiment by delegating > 50% of total ADAs of the network to active pools, evenly or not, to check the effect on block production ?

**Comment by rdlrt** [comment]
As discussed in group, temporarily delegated 97% to your pool (for a day). Will revert to have 60% in circulation and divide between each of the pools to distribute leadership tasks evenly again
