### ISSUE TITLE
Feature Request: Incorporate Pooltool Feature Send_slots.sh

### ISSUE THREAD

**Issue by arussell29** [rdlrt/Alternate-Jormungandr-Testnet#70]
This is a request to incorporate and optionally enable Pooltool's send_slots.sh functionality into leaders-failover script once the slot tracking function is Pooltool is in production. Can this please be supported?

**Comment by rdlrt** [comment]
Added with [this ](https://github.com/rdlrt/Alternate-Jormungandr-Testnet/commit/0f3f9a7591015ac2c79e10f2264d59855649352c) commit (to enable, you'd need to set pooltoolreportmode=2, let me know if any issues.

**Comment by rdlrt** [comment]
Closed as the updated script is now on master (with a bugfix)
