### ISSUE TITLE
assigned slot count not sent to Pooltool using leaders-failover.sh

### ISSUE THREAD

**Issue by samcgill29** [rdlrt/Alternate-Jormungandr-Testnet#71]
Using jormungandr 0.8.13 (heads/v0.8.13-241b3a59, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]
and
jcli 0.8.13 (heads/v0.8.13-241b3a59, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

Ubuntu 18.04 LTS linux VPS

Utilized latest release of leaders-failover.sh script (with recent commit: correct currslots_enc...) but pooltool did not report back the assigned slots count.  Pooltool response was:

10/03-20:13:52 -  - Pooltool Response for slot logs: {"success": true, "message"  : {"assigned_slots_saved": " ", "encrypted_slots_saved": true}}

There should be a number following "assigned_slots_saved" Leader has 10 slots assigned this epoch.

It seems that the script is not reporting a number for the assigned slot count. Correct behavior would be to report this number.

**Comment by rdlrt** [comment]
@samcgill29 Thanks for the report. Do you have any errors in stderr log? Also, could you share your stdout from the script (to gather the timings and epoch transition exit details)?

**Comment by samcgill29** [comment]
The only thing in stderr.log is one line:
gpg: keybox '/home/jormu/.gnupg/pubring.kbx' created

stdout content follows:
10/03-20:13:33 -  - Entered: Adding keys, pausing failover capabilities..
10/03-20:13:53 -  - Waiting for Schedule: Iteration - (16/300) ..
10/03-20:13:54 -  - Complete: Schedule loaded successfully
10/03-20:13:57 -  - Pooltool Response for slot logs: {"success": true, "message": {"assigned_slots_saved": " ", "encrypted_slots_saved": true}}

**Comment by rdlrt** [comment]
Thanks for the details, it was likely due to invalid env variable reference. Should be fixed on master now
